const competitors = [
    {
      name: "TechCorp",
      sector: "Технології",
      capital: 1000000000,
      address: "Silicon Valley",
      financials: "Стабільний ріст",
      trends: "AI, Cloud",
      opportunities: "Розширення на Європу",
      employees: 5000,
      marketShare: 25,
      founded: 2008,
      ceo: "John Smith",
      image: "/assets/images/graphic_up.jpg",
      revenue: 250000000,
      expenses: 100000000
    },
    {
      name: "FinServe",
      sector: "Фінанси",
      capital: 500000000,
      address: "London, UK",
      financials: "Прибуток зростає",
      trends: "Fintech, Blockchain",
      opportunities: "Нові фінансові послуги",
      employees: 1200,
      marketShare: 15,
      founded: 2015,
      ceo: "Emma Johnson",
      image: "/assets/images/graphic_down.jpg",
      revenue: 180000000,
      expenses: 70000000
    },
    {
      name: "EnergyNet",
      sector: "Енергетика",
      capital: 2000000000,
      address: "Berlin, Germany",
      financials: "Висока стабільність",
      trends: "Зелена енергетика",
      opportunities: "Інвестиції в нові технології",
      employees: 8000,
      marketShare: 30,
      founded: 2000,
      ceo: "Michael Brown",
      image: "/assets/images/graphic_down.jpg",
      revenue: 600000000,
      expenses: 320000000
    },
    {
      name: "AutoDrive",
      sector: "Автомобілі",
      capital: 3000000000,
      address: "Detroit, USA",
      financials: "Постійне зростання",
      trends: "Електрокари, Автопілот",
      opportunities: "Розширення на азійський ринок",
      employees: 10000,
      marketShare: 20,
      founded: 2012,
      ceo: "David White",
      image: "/assets/images/graphic_down.jpg",
      revenue: 750000000,
      expenses: 400000000
    },
    {
      name: "FoodTech",
      sector: "Харчова промисловість",
      capital: 700000000,
      address: "Paris, France",
      financials: "Інноваційні продукти",
      trends: "Альтернативні білки",
      opportunities: "Глобальне розширення",
      employees: 3500,
      marketShare: 10,
      founded: 2010,
      ceo: "Sophie Martin",
      image: "/assets/images/graphic_up.jpg",
      revenue: 220000000,
      expenses: 110000000
    },
    {
      name: "EduTech",
      sector: "Освіта",
      capital: 900000000,
      address: "Toronto, Canada",
      financials: "Швидке зростання",
      trends: "Онлайн-навчання",
      opportunities: "Корпоративний сегмент",
      employees: 2500,
      marketShare: 12,
      founded: 2017,
      ceo: "Robert King",
      image: "/assets/images/graphic_down.jpg",
      revenue: 300000000,
      expenses: 140000000
    },
    {
      name: "HealthPlus",
      sector: "Медицина",
      capital: 2500000000,
      address: "Zurich, Switzerland",
      financials: "Стабільний ріст",
      trends: "Дистанційна медицина",
      opportunities: "Інвестиції в AI",
      employees: 7500,
      marketShare: 28,
      founded: 1995,
      ceo: "Laura Green",
      image: "/assets/images/graphic_up.jpg",
      revenue: 800000000,
      expenses: 400000000
    },
    {
      name: "CloudSync",
      sector: "Хмарні технології",
      capital: 1200000000,
      address: "Seattle, USA",
      financials: "Зростання клієнтів",
      trends: "Кібербезпека",
      opportunities: "Бізнес-рішення",
      employees: 6800,
      marketShare: 22,
      founded: 2005,
      ceo: "Richard Adams",
      image: "/assets/images/graphic_up.jpg",
      revenue: 400000000,
      expenses: 210000000
    },
    {
      name: "AgroNova",
      sector: "Сільське господарство",
      capital: 600000000,
      address: "Kyiv, Ukraine",
      financials: "Сезонне зростання",
      trends: "AgriTech, Дрони",
      opportunities: "Автоматизація ферм",
      employees: 2300,
      marketShare: 9,
      founded: 2014,
      ceo: "Oleh Shevchenko",
      image: "/assets/images/graphic_up.jpg",
      revenue: 170000000,
      expenses: 80000000
    },
    {
      name: "BuildSmart",
      sector: "Інфраструктура",
      capital: 1800000000,
      address: "Warsaw, Poland",
      financials: "Нестабільна динаміка",
      trends: "Smart Cities",
      opportunities: "Публічні тендери",
      employees: 5400,
      marketShare: 16,
      founded: 2001,
      ceo: "Anna Kowalska",
      image: "/assets/images/graphic_down.jpg",
      revenue: 320000000,
      expenses: 250000000
    },
    {
      name: "RoboWare",
      sector: "Робототехніка",
      capital: 2100000000,
      address: "Tokyo, Japan",
      financials: "Інтенсивне зростання",
      trends: "Промислові роботи",
      opportunities: "Світовий ринок",
      employees: 7200,
      marketShare: 18,
      founded: 1999,
      ceo: "Takeshi Nakamura",
      image: "/assets/images/graphic_up.jpg",
      revenue: 540000000,
      expenses: 300000000
    },
    {
      name: "TransLogix",
      sector: "Логістика",
      capital: 850000000,
      address: "Hamburg, Germany",
      financials: "Стабільність",
      trends: "Автоматизація складів",
      opportunities: "Міжнародні перевезення",
      employees: 4100,
      marketShare: 14,
      founded: 2007,
      ceo: "Karl Meier",
      image: "/assets/images/graphic_down.jpg",
      revenue: 280000000,
      expenses: 160000000
    },
    {
      name: "BioGenics",
      sector: "Біотехнології",
      capital: 1600000000,
      address: "Boston, USA",
      financials: "Інноваційний прорив",
      trends: "Генна інженерія",
      opportunities: "Ліцензування патентів",
      employees: 3900,
      marketShare: 19,
      founded: 2011,
      ceo: "Jessica Brown",
      image: "/assets/images/graphic_up.jpg",
      revenue: 470000000,
      expenses: 230000000
    }
  ];
  
  export default competitors;
  